package response

// 自定义错误码与错误信息

const (
	// Ok ...
	Ok = 200
	// NotOk ...
	NotOk = 400
	// Unauthorized ...
	Unauthorized = 401
	// Forbidden ...
	Forbidden = 403
	// ParmError ...
	ParmError = 406
	// InternalServerError ...
	InternalServerError = 500
	// AuthError ...
	AuthError = 1000
	// UserForbidden ...
	UserForbidden = 1001
)

const (
	// OkMsg ...
	OkMsg = "操作成功"
	// NotOkMsg ...
	NotOkMsg = "操作失败"
	// UnauthorizedMsg ...
	UnauthorizedMsg = "登录过期, 需要重新登录"
	// LoginCheckErrorMsg ...
	LoginCheckErrorMsg = "用户名或密码错误"
	// ForbiddenMsg ...
	ForbiddenMsg = "无权访问该资源"
	// InternalServerErrorMsg ...
	InternalServerErrorMsg = "服务器内部错误"
	// ParmErrorMsg ...
	ParmErrorMsg = "参数绑定失败, 请检查数据类型"
	// UserForbiddenMsg ...
	UserForbiddenMsg = "用户已被禁用"
)

// CustomError ...
var CustomError = map[int]string{
	Ok:                  OkMsg,
	NotOk:               NotOkMsg,
	Unauthorized:        UnauthorizedMsg,
	Forbidden:           ForbiddenMsg,
	InternalServerError: InternalServerErrorMsg,
	AuthError:           LoginCheckErrorMsg,
	ParmError:           ParmErrorMsg,
	UserForbidden:       UserForbiddenMsg,
}
